services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173'
    volumes:
      - .:/folders-tree
      - /folders-tree/node_modules
    command: npm run start
