name: Create Docker Image

on:
  push:
    branches:
      - 'main'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [lint, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run task
        run: npm run ${{ matrix.task }}

  create-docker-image:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker Compose services
        run: docker-compose -f docker-compose.prod.yml build

      - name: Tag Docker image
        run: docker tag folders-tree_react-app:latest ${{ vars.DOCKERHUB_USERNAME }}/folders-tree:latest

      - name: Push Docker image
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/folders-tree:latest
